/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Wiew;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
    }

    

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            // Color color1 =new Color(4,119,191);
            // Color color2=new Color(65,159,217);
            Color color2 = new Color(4, 119, 191);
            Color color1 = new Color(65, 159, 217);

            GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    
     

        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new jPanelGradient();
        btCalendario = new javax.swing.JButton();
        btHistórico = new javax.swing.JButton();
        btPendentes = new javax.swing.JButton();
        btEdicao = new javax.swing.JButton();
        btConfig = new javax.swing.JButton();
        btDesconectar = new javax.swing.JButton();
        edName = new javax.swing.JLabel();
        btTelaPrincipal = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtAbrirTelaDeRelatorio = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 119, 191));

        btCalendario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btCalendario.setForeground(new java.awt.Color(242, 242, 242));
        btCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/simbolo-de-ferramentas-de-organizacao-e-administracao-de-horario-de-calendario-e-relogio (1).png"))); // NOI18N
        btCalendario.setText(" Calendario");
        btCalendario.setBorder(null);
        btCalendario.setBorderPainted(false);
        btCalendario.setContentAreaFilled(false);
        btCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCalendarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCalendarioMouseExited(evt);
            }
        });
        btCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalendarioActionPerformed(evt);
            }
        });

        btHistórico.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btHistórico.setForeground(new java.awt.Color(242, 242, 242));
        btHistórico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/historia.png"))); // NOI18N
        btHistórico.setText(" Historico");
        btHistórico.setBorder(null);
        btHistórico.setBorderPainted(false);
        btHistórico.setContentAreaFilled(false);
        btHistórico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btHistóricoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btHistóricoMouseExited(evt);
            }
        });
        btHistórico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistóricoActionPerformed(evt);
            }
        });

        btPendentes.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btPendentes.setForeground(new java.awt.Color(242, 242, 242));
        btPendentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/expirado.png"))); // NOI18N
        btPendentes.setText(" Pendentes");
        btPendentes.setBorder(null);
        btPendentes.setBorderPainted(false);
        btPendentes.setContentAreaFilled(false);
        btPendentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPendentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPendentesMouseExited(evt);
            }
        });
        btPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPendentesActionPerformed(evt);
            }
        });

        btEdicao.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btEdicao.setForeground(new java.awt.Color(242, 242, 242));
        btEdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edicao.png"))); // NOI18N
        btEdicao.setText(" Edição");
        btEdicao.setBorder(null);
        btEdicao.setBorderPainted(false);
        btEdicao.setContentAreaFilled(false);
        btEdicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btEdicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btEdicaoMouseExited(evt);
            }
        });
        btEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdicaoActionPerformed(evt);
            }
        });

        btConfig.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btConfig.setForeground(new java.awt.Color(242, 242, 242));
        btConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/configuracoes.png"))); // NOI18N
        btConfig.setText(" Configurações");
        btConfig.setBorder(null);
        btConfig.setBorderPainted(false);
        btConfig.setContentAreaFilled(false);
        btConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btConfigMouseExited(evt);
            }
        });
        btConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfigActionPerformed(evt);
            }
        });

        btDesconectar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btDesconectar.setForeground(new java.awt.Color(242, 242, 242));
        btDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sair.png"))); // NOI18N
        btDesconectar.setText(" Desconectar");
        btDesconectar.setBorder(null);
        btDesconectar.setBorderPainted(false);
        btDesconectar.setContentAreaFilled(false);
        btDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDesconectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDesconectarMouseExited(evt);
            }
        });
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });

        edName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        edName.setForeground(new java.awt.Color(242, 242, 242));
        edName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user 32.png"))); // NOI18N
        edName.setText("YourName");

        btTelaPrincipal.setBackground(new java.awt.Color(4, 119, 191));
        btTelaPrincipal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btTelaPrincipal.setForeground(new java.awt.Color(242, 242, 242));
        btTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user (24.png"))); // NOI18N
        btTelaPrincipal.setText(" Menu Principal");
        btTelaPrincipal.setBorder(null);
        btTelaPrincipal.setBorderPainted(false);
        btTelaPrincipal.setContentAreaFilled(false);
        btTelaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btTelaPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btTelaPrincipalMouseExited(evt);
            }
        });
        btTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelaPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPendentes)
                            .addComponent(btEdicao)
                            .addComponent(btConfig)
                            .addComponent(btDesconectar))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btHistórico)
                            .addComponent(btCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btTelaPrincipal)
                            .addComponent(edName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(btTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btHistórico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(btConfig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 650));

        jPanel6.setBackground(new java.awt.Color(213, 229, 242));

        jButton4.setBackground(new java.awt.Color(4, 119, 191));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(4, 119, 191));
        jButton4.setText("X");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 860, Short.MAX_VALUE)
                .addComponent(jButton4))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 890, 30));

        jTabbedPane1.setBackground(new java.awt.Color(244, 244, 244));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Form1");

        BtAbrirTelaDeRelatorio.setText("Abrir tela de relatório");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(BtAbrirTelaDeRelatorio)))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addGap(125, 125, 125)
                .addComponent(BtAbrirTelaDeRelatorio)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(244, 244, 244));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Form2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel2)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel5.setBackground(new java.awt.Color(244, 244, 244));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Form3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel3)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel3)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel7.setBackground(new java.awt.Color(244, 244, 244));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Form4");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel4)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel4)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel7);

        jPanel8.setBackground(new java.awt.Color(244, 244, 244));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Form5");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel5)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel5)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel8);

        jPanel9.setBackground(new java.awt.Color(244, 244, 244));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Form6");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel6)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel6)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", jPanel9);

        jPanel10.setBackground(new java.awt.Color(244, 244, 244));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Form7");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel7)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel7)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab7", jPanel10);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -10, 840, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btCalendarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCalendarioMouseEntered
        btCalendario.setForeground(new Color(178, 190, 191));
    }//GEN-LAST:event_btCalendarioMouseEntered

    private void btCalendarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCalendarioMouseExited
        btCalendario.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_btCalendarioMouseExited

    private void btHistóricoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHistóricoMouseEntered
        btHistórico.setForeground(new Color(178, 190, 191));
    }//GEN-LAST:event_btHistóricoMouseEntered

    private void btHistóricoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHistóricoMouseExited
        btHistórico.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_btHistóricoMouseExited

    private void btPendentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPendentesMouseEntered
        btPendentes.setForeground(new Color(178, 190, 191));
    }//GEN-LAST:event_btPendentesMouseEntered

    private void btPendentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPendentesMouseExited
        btPendentes.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_btPendentesMouseExited

    private void btEdicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEdicaoMouseEntered
        btEdicao.setForeground(new Color(178, 190, 191));
    }//GEN-LAST:event_btEdicaoMouseEntered

    private void btEdicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEdicaoMouseExited
        btEdicao.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_btEdicaoMouseExited

    private void btConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfigMouseEntered
        btConfig.setForeground(new Color(178, 190, 191));
    }//GEN-LAST:event_btConfigMouseEntered

    private void btConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfigMouseExited
        btConfig.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_btConfigMouseExited

    private void btDesconectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesconectarMouseEntered
        btDesconectar.setForeground(new Color(178, 190, 191));
    }//GEN-LAST:event_btDesconectarMouseEntered

    private void btDesconectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesconectarMouseExited
        btDesconectar.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_btDesconectarMouseExited

    private void btTelaPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTelaPrincipalMouseEntered
        btTelaPrincipal.setForeground(new Color(178, 190, 191));

    }//GEN-LAST:event_btTelaPrincipalMouseEntered

    private void btTelaPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTelaPrincipalMouseExited
        btTelaPrincipal.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_btTelaPrincipalMouseExited

    private void btTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelaPrincipalActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btTelaPrincipalActionPerformed

    private void btCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalendarioActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btCalendarioActionPerformed

    private void btHistóricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistóricoActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btHistóricoActionPerformed

    private void btPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPendentesActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btPendentesActionPerformed

    private void btEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdicaoActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btEdicaoActionPerformed

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_btDesconectarActionPerformed

    private void btConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfigActionPerformed
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_btConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtAbrirTelaDeRelatorio;
    public javax.swing.JButton btCalendario;
    public javax.swing.JButton btConfig;
    public javax.swing.JButton btDesconectar;
    public javax.swing.JButton btEdicao;
    public javax.swing.JButton btHistórico;
    public javax.swing.JButton btPendentes;
    public javax.swing.JButton btTelaPrincipal;
    public javax.swing.JLabel edName;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
