# Generated by Django 5.1.6 on 2025-07-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinica',
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
