package tcc.application.form.other;

import com.sun.tools.javac.Main;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.TableCellEditor;

public class PanelAction extends javax.swing.JPanel {

    private FormMainMenu fmm;
    private TableActionEvent event;
    private TableCellEditor editor;
    private int currentRow = -1;

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        fmm = new FormMainMenu();
        initComponents();
        cmdC.setForeground(fmm.MainTable.getBackground());
        cmdX.setForeground(fmm.MainTable.getBackground());

    }
    
    public void updateRow(int row) {
        this.currentRow = row;

        // Remove todos os ActionListeners anteriores
        for (ActionListener al : cmdC.getActionListeners()) {
            cmdC.removeActionListener(al);
        }
        for (ActionListener al : cmdX.getActionListeners()) {
            cmdX.removeActionListener(al);
        }

        // Adiciona novamente os listeners com a linha correta
        cmdC.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (event != null) {
                    event.onFinish(currentRow);
                }
                if (editor != null) {
                    editor.stopCellEditing();
                }
            }
        });
    }
    
    
    

    public void initEvent(TableActionEvent event, int row, TableCellEditor editor) {
        cmdC.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onFinish(row);
                if (editor != null) {
                    editor.stopCellEditing(); // <- encerra a edição
                }

            }
        });
        cmdX.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
                if (editor != null) {
                    editor.stopCellEditing(); // <- encerra a edição
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdX = new ActionButton();
        cmdC =  new ActionButton();

        cmdX.setForeground(new java.awt.Color(102, 0, 102));
        cmdX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/application/form/other/delete.png"))); // NOI18N
        cmdX.setContentAreaFilled(false);

        cmdC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/application/form/other/certo (2).png"))); // NOI18N
        cmdC.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdC)
                    .addComponent(cmdX))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdC;
    private javax.swing.JButton cmdX;
    // End of variables declaration//GEN-END:variables
}
