# Generated by Django 5.1.6 on 2025-07-25 00:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField()),
                ('caminho_documentos', models.CharField(blank=True, default='Sem documento', max_length=255)),
                ('type', models.CharField(db_column='type', max_length=255)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='AGENDADA', max_length=50)),
                ('descricao', models.CharField(blank=True, default='Nenhuma descrição', max_length=255)),
                ('motivo_cancelamento', models.CharField(blank=True, default='Não cancelado', max_length=255)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horarios', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateTimeField()),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('data_nascimento', models.DateField()),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('type', models.CharField(blank=True, max_length=7, null=True)),
                ('sexo', models.CharField()),
                ('is_verified', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_pessoa', models.OneToOneField(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.pessoa')),
                ('crm', models.CharField(max_length=255)),
                ('tipo_medico', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_pessoa', models.OneToOneField(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.pessoa')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to='accounts.pessoa')),
            ],
            options={
                'db_table': 'email_verification_token',
            },
        ),
    ]
