# Generated by Django 5.1.6 on 2025-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('iniciomanha', models.TimeField()),
                ('fimmanha', models.TimeField()),
                ('iniciotarde', models.TimeField()),
                ('fimtarde', models.TimeField()),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
